# Jekyll configuration

name: Lierally Malware
description: Cyber Security

# Url is currently only used only for the RSS feed in feed.xml
url: https://literallymalwa.re
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: ThePraeceps
copyright: 2015-2018

share:
  facebook: false
  twitter: false
  gplus: false  
  linkedin: false
  pinterest: false
  email: false

social:
  github: ThePraeceps
  rss: feed.xml



# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
